# Generated by Django 4.1.2 on 2022-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0002_ratingsetup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingsetup",
            name="display_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
