# Generated by Django 4.1.3 on 2022-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0003_alter_ratingsetup_display_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratingsetup",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ratingsetup",
            name="display_image",
        ),
        migrations.RemoveField(
            model_name="ratingsetup",
            name="display_text",
        ),
        migrations.RemoveField(
            model_name="ratingsetup",
            name="is_active",
        ),
        migrations.AddField(
            model_name="ratingsetup",
            name="negative_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/rating/"),
        ),
        migrations.AddField(
            model_name="ratingsetup",
            name="positive_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/rating/"),
        ),
    ]
