# Generated by Django 4.1.3 on 2022-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0004_remove_ratingsetup_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingsetup",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
