# Generated by Django 4.1.2 on 2022-12-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0006_roomsetup_room_idenfier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert_history",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("parameter", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertConditions",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_conditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEmailHistory",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("parameter", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("alert", models.JSONField()),
                ("is_email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_email_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
