# Generated by Django 4.1.2 on 2022-12-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0007_alert_history_alertconditions_alertemailhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertemailhistory",
            old_name="alert",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="alertemailhistory",
            old_name="value",
            new_name="threshold",
        ),
        migrations.RemoveField(
            model_name="alert_history",
            name="value",
        ),
        migrations.AddField(
            model_name="alert_history",
            name="is_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
