# Generated by Django 4.1.2 on 2022-12-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restroom", "0008_rename_alert_alertemailhistory_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlertEmailHistory",
        ),
    ]
