# Generated by Django 4.1.2 on 2022-11-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mqttsetup",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="mqttsetup",
            name="password",
        ),
        migrations.RemoveField(
            model_name="mqttsetup",
            name="port",
        ),
        migrations.RemoveField(
            model_name="mqttsetup",
            name="username",
        ),
    ]
