# Generated by Django 4.1.2 on 2022-11-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0002_remove_mqttsetup_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mqttsetup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mqttsetup",
            name="updated_by",
        ),
    ]
