# Generated by Django 4.1.2 on 2022-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0003_remove_mqttsetup_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aqi",
            name="room",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
