# Generated by Django 4.1.2 on 2022-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0004_alter_aqi_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootFall",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Footfall", max_length=100)),
                ("data", models.JSONField()),
                ("room", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "footfall",
            },
        ),
    ]
